export const PREFIX = "@@auth/";

export const ASYNC_AUTH_INIT = `${PREFIX}ASYNC_AUTH_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const AUTH_SIGN_UP_SUCCESS = `${PREFIX}AUTH_SIGN_UP_SUCCESS`;
export const AUTH_SIGN_IN_SUCCESS = `${PREFIX}AUTH_SIGN_IN_SUCCESS`;
export const AUTH_SIGN_OUT_SUCCESS = `${PREFIX}AUTH_SIGN_OUT_SUCCESS`;
export const AUTH_AUTHENTICATION_FAILURE = `${PREFIX}AUTH_AUTHENTICATION_FAILURE`;
