export const PREFIX = "@@employee/";

export const ASYNC_EMPLOYEE_INIT = `${PREFIX}ASYNC_EMPLOYEE_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const INIT_EMPLOYEE = `${PREFIX}INIT_EMPLOYEE`;
export const INITIALIZE_EMPLOYEE = `${PREFIX}INITIALIZE_EMPLOYEE`;

export const GET_EMPLOYEE_SUCCESS = `${PREFIX}GET_EMPLOYEE_SUCCESS`;
export const GET_EMP_SUCCESS = `${PREFIX}GET_EMP_SUCCESS`;
