export const PREFIX = "@@orders/";

export const ASYNC_ORDERS_INIT = `${PREFIX}ASYNC_ORDERS_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const INIT_ORDERS = `${PREFIX}INIT_ORDERS`;

export const GET_ORDERS_SUCCESS = `${PREFIX}GET_ORDERS_SUCCESS`;
export const GET_ORDER_SUCCESS = `${PREFIX}GET_ORDER_SUCCESS`;
