export const PREFIX = "@@product/";

export const ASYNC_PRODUCT_INIT = `${PREFIX}ASYNC_PRODUCT_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;
export const INIT_PRODUCT = `${PREFIX}INIT_PRODUCT`;
export const INITIALIZE_PRODUCT = `${PREFIX}INITIALIZE_PRODUCT`;

export const GET_PRODUCTS_SUCCESS = `${PREFIX}GET_PRODUCTS_SUCCESS`;
export const GET_PRODUCT_SUCCESS = `${PREFIX}GET_PRODUCT_SUCCESS`;
