export const PREFIX = "@@sale/";

export const ASYNC_SALE_INIT = `${PREFIX}ASYNC_SALE_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_SALES_SUCCESS = `${PREFIX}GET_SALES_SUCCESS`;
