export const PREFIX = "@@user/";

export const ASYNC_USER_INIT = `${PREFIX}ASYNC_USER_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_USERS_SUCCESS = `${PREFIX}GET_USERS_SUCCESS`;
export const GET_USER_SUCCESS = `${PREFIX}GET_USER_SUCCESS`;
